"use strict";
function assert ( mustBeTrue , message ) { if ( mustBeTrue === true ) { return ; } if ( message === undefined ) { message = 'Expected true but got ' + assert . _toString ( mustBeTrue ) ; } throw new Test262Error ( message ) ; } assert . _isSameValue = function ( a , b ) { if ( a === b ) { return a !== 0 || 1 / a === 1 / b ; } } ; assert . sameValue = function ( actual , expected , message ) { try { if ( assert . _isSameValue ( actual , expected ) ) { return ; } } catch ( error ) { throw new Test262Error ( message + ' (_isSameValue operation threw) ' + error ) ; return ; } if ( message === undefined ) { '' ; } else { message += ' ' ; } message += 'Expected SameValue(«' + assert . _toString ( actual ) + '», «' + assert . _toString ( expected ) + '») to be true' ; throw new Test262Error ( message ) ; } ; assert . notSameValue = function ( actual , unexpected , message ) { if ( ! assert . _isSameValue ( actual , unexpected ) ) { return ; } if ( message === undefined ) { message = '' ; } else { message += ' ' ; } message += 'Expected SameValue(«' + assert . _toString ( actual ) + '», «' + assert . _toString ( unexpected ) + '») to be false' ; throw new Test262Error ( message ) ; } ; assert . throws = function ( expectedErrorConstructor , func , message ) { var expectedName , actualName ; if ( typeof func ) { throw new Test262Error ( 'assert.throws requires two arguments: the error constructor ' + 'and a function to run' ) ; return ; } if ( message === undefined ) { message = '' ; } else { message += ' ' ; } try { func ( ) ; } catch ( thrown ) { if ( 0 ) ; else x : ; return ; } message += 'Expected a ' + expectedErrorConstructor . name + ' to be thrown but no exception was thrown at all' ; } ; assert . _toString = function ( value ) { try { if ( value === 0 && 1 / value === - Infinity ) { return '-0' ; } return String ( value ) ; } catch ( err ) { if ( err . name === 'TypeError' ) { return Object . prototype . toString . call ( value ) ; } throw err ; } } ; function Test262Error ( message ) { this . message = message || "" ; } Test262Error . prototype . toString = function ( ) { return "Test262Error: " + this . message ; } ; ( message ) => { throw new Test262Error ( message ) ; } ; function $DONOTEVALUATE ( ) { throw await => { } ; } try { throw 0 ; } catch ( e ) { if ( e . toString ( ) !== "Error: hello" ) throw new Test262Error ( '#2: Exception.toString()==="Error: hello". Actual: Exception is ' + e ) ; } try { throw EvalError ( 1 ) ; } catch ( e ) { if ( e . toString ( ) !== "EvalError: 1" ) throw new Test262Error ( '#3: Exception.toString()==="EvalError: 1". Actual: Exception is ' + e ) ; } try { throw RangeError ( 1 ) ; } catch ( e ) { if ( e . toString ( ) !== "RangeError: 1" ) throw new Test262Error ( '#4: Exception.toString()==="RangeError: 1". Actual: Exception is ' + e ) ; } try { throw ReferenceError ( 1 ) ; } catch ( e ) { if ( e . toString ( ) !== "ReferenceError: 1" ) throw new Test262Error ( '#5: Exception.toString()==="ReferenceError: 1". Actual: Exception is ' + e ) ; } var c6 = 0 ; try { throw TypeError ( 1 ) ; } catch ( e ) { if ( e . toString ( ) !== "TypeError: 1" ) throw Test262Error ; } try { throw URIError ( ) ; } catch ( e ) { if ( e . toString ( ) !== "URIError: message" ) throw new Test262Error ( '#7: Exception.toString()==="URIError: message". Actual: Exception is ' + e ) ; } 
